import AVFAudio
import os

/// Which sound an alarm makes. A room and a monitoring failure never sound
/// alike, so one is never mistaken for the other at 3 am
/// (shared/spec/failure-alerts.md, "How it is said").
///
/// - AlarmKit plays a room with the **system alarm sound** (the spec's "the
///   phone's alarm sound") and a failure with `monitoring_failure.caf`.
/// - The fallback plays both through the engine, which cannot reach the
///   system's alarm sounds, so a room gets the bundled `room_alarm.caf`.
///
/// The files are 48 kHz mono 16-bit linear PCM in CAF, which AlarmKit and
/// notifications accept as a named sound and the engine plays as is.
/// `monitoring_failure.caf` is Android's `res/raw/monitoring_failure.wav`
/// converted; `room_alarm.caf` is generated by `ios/tools/alarm-tone.py`. Both
/// are the project's own.
enum AlarmTone: Sendable, CaseIterable {
    case room
    case failure

    /// The file in the main bundle, as AlarmKit and notifications name it.
    var fileName: String {
        switch self {
        case .room: "room_alarm.caf"
        case .failure: "monitoring_failure.caf"
        }
    }

    private static let log = Logger(subsystem: "app.dozecam", category: "alerts")

    /// The tone decoded for the engine, or nil when the file is missing or
    /// unreadable (logged: a build without its tones is a broken build).
    func load(from bundle: Bundle = .main) -> AlarmToneBuffer? {
        let name = (fileName as NSString).deletingPathExtension
        let type = (fileName as NSString).pathExtension
        guard let url = bundle.url(forResource: name, withExtension: type) else {
            Self.log.fault("alarm tone \(fileName, privacy: .public) is not in the bundle")
            return nil
        }
        do {
            return AlarmToneBuffer(samples: try Self.decode(url))
        } catch {
            Self.log.fault("alarm tone \(fileName, privacy: .public) unreadable: \(error, privacy: .public)")
            return nil
        }
    }

    /// Mono Float samples at `SpeakerMix.sampleRate`, converted if the file
    /// is at another rate or has more channels.
    static func decode(_ url: URL) throws -> [Float] {
        let file = try AVAudioFile(forReading: url)
        let target = AVAudioFormat(standardFormatWithSampleRate: SpeakerMix.sampleRate, channels: 1)!
        let source = file.processingFormat
        let frames = AVAudioFrameCount(file.length)
        guard frames > 0, let input = AVAudioPCMBuffer(pcmFormat: source, frameCapacity: frames) else { return [] }
        try file.read(into: input)
        let output: AVAudioPCMBuffer
        if source.sampleRate == target.sampleRate, source.channelCount == 1,
            source.commonFormat == .pcmFormatFloat32
        {
            output = input
        } else {
            guard let converter = AVAudioConverter(from: source, to: target) else { throw DecodeError.noConverter }
            let capacity = AVAudioFrameCount(Double(frames) * target.sampleRate / source.sampleRate) + 1_024
            guard let converted = AVAudioPCMBuffer(pcmFormat: target, frameCapacity: capacity) else {
                throw DecodeError.noConverter
            }
            nonisolated(unsafe) var consumed = false
            var failure: NSError?
            let status = converter.convert(to: converted, error: &failure) { _, inputStatus in
                if consumed {
                    inputStatus.pointee = .endOfStream
                    return nil
                }
                consumed = true
                inputStatus.pointee = .haveData
                return input
            }
            if status == .error { throw failure ?? DecodeError.noConverter }
            output = converted
        }
        guard let channel = output.floatChannelData?[0] else { return [] }
        return Array(UnsafeBufferPointer(start: channel, count: Int(output.frameLength)))
    }

    enum DecodeError: Error {
        case noConverter
    }
}
